{
 "title": "kdb sample metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "SM EOI Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kxi_sm_eoi_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SM EOD Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kxi_sm_eod_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HDB size ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kxi_sm_hdb_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Services RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "memory_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Records at EOI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kxi_sm_eoi_records", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Msgs received - RDB",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "kxi_da_stream_msgs{instance=\"rdb-sidecar:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Requests - DA, SG, RC, AGG",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expr": "kxi_da_requests", "legendFormat": "__auto" },
    { "expr": "kxi_sg_ipc_requests_total", "legendFormat": "__auto" },
    { "expr": "kxi_rc_reqs_total", "legendFormat": "__auto" },
    { "expr": "kxi_agg_ipc_reqs", "legendFormat": "__auto" }
   ]
  }
 ]
}