{
 "title": "kdb sample metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Number of Msgs received - RDB",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kxi_da_stream_msgs{instance=\"rdb-sidecar:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Records at EOI",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kxi_sm_eoi_records", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DA Query Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "kxi_da_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Services RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "memory_usage_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}