name: "trade-assembly"
description: "Sample assembly file"

labels:
  user: root

tables:
  trade:
    description: Trade data
    type: partitioned
    blockSize: 10000
    prtnCol: time
    sortColsOrd: sym
    sortColsDisk: sym
    columns:
      - name: time
        description: Time
        type: timestamp    
      - name: sym
        description: Symbol name
        type: symbol
        attrMem: grouped
        attrDisk: parted
        attrOrd: parted
      - name: price
        description: Price
        type: float    
      - name: size
        description: Size
        type: long      

  quote:
    description: Quote data
    type: partitioned
    blockSize: 10000
    prtnCol: time
    sortColsOrd: sym
    sortColsDisk: sym
    columns:
      - name: time
        description: Time
        type: timestamp    
      - name: sym
        description: Symbol name
        type: symbol
        attrMem: grouped
        attrDisk: parted
        attrOrd: parted
      - name: bid
        description: bid price
        type: float    
      - name: ask
        description: bid price
        type: float   
      - name: bsize
        description: bid price
        type: long  
      - name: asize
        description: bid price
        type: long                  

# bus:
#   stream:
#     protocol: custom
#     nodes: tp:5010
#     topic: dataStream

bus:
  stream:
    protocol: rt
    topic: data
    topicPrefix: rt-
    nodes:
    - rt-data-0:5001
    - rt-data-1:5001
    - rt-data-2:5001



mounts:
  rdb:
    type: stream
    baseURI: file:///mnt/foo/i/
    partition: none
  idb:
    type: local
    baseURI: file://${mnt_dir}/idb
    partition: ordinal
  hdb:
    type: local
    baseURI: file://${mnt_dir}/hdb
    partition: date

elements:
  dap:
    # gwAssembly: sgrc:5060 
    # gwEndpoints: sgrc:5060    
    smEndpoints: sm:10001
    instances:
      dap:
        mountList: [rdb, idb, hdb]

  sm:
    description: Storage manager
    source: stream
    tiers:
      - name: stream
        mount: rdb
      - name: idb
        mount: idb
        schedule:
          freq: 0D00:10:00      # every 10 minutes
          snap: 0D00:00:00
      - name: hdb
        mount: hdb
        retain: 
          time: 30 days
    disableDiscovery: true  # Disables registering with discovery