{
 "title": "kdb sample metrics",
 "time": { "from": "2023-10-06T19:00:18.162Z", "to": "2023-10-06T19:20:18.162Z" },
 "panels": [
  {
   "title": "DA Query Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kxi_da_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Msgs received - RDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "kxi_da_stream_msgs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Records at EOI",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kxi_sm_eoi_records", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Services RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "memory_usage_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}